import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Search from "@/components/Search";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Search />
        <main className="container mx-auto my-7">{children}</main>
      </body>
    </html>
  );
}
